"""Add users table and professional relationship

Revision ID: 0394003e85c7
Revises: 66beee68eae2
Create Date: 2026-06-02 22:59:51.175858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0394003e85c7'
down_revision: Union[str, Sequence[str], None] = '66beee68eae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN_CENTRO', 'PROFESIONAL', 'SECRETARIA', name='userrole'), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('professionals', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'professionals', ['user_id'])
    op.create_foreign_key(None, 'professionals', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'professionals', type_='foreignkey')
    op.drop_constraint(None, 'professionals', type_='unique')
    op.drop_column('professionals', 'user_id')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
