"""add_clinical_records

Revision ID: 8438801218ef
Revises: 0394003e85c7
Create Date: 2026-06-02 23:40:58.686690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8438801218ef'
down_revision: Union[str, Sequence[str], None] = '0394003e85c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("COMMIT")
        op.execute("ALTER TYPE appointmentstate ADD VALUE IF NOT EXISTS 'ATENDIDO'")
        
    op.create_table('clinical_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_index(op.f('ix_clinical_files_id'), 'clinical_files', ['id'], unique=False)
    op.create_table('clinical_consultations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinical_file_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('fecha_atencion', sa.DateTime(), nullable=False),
    sa.Column('motivo_consulta', sa.String(length=255), nullable=False),
    sa.Column('evolucion_dinamica', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['clinical_file_id'], ['clinical_files.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id')
    )
    op.create_index(op.f('ix_clinical_consultations_id'), 'clinical_consultations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinical_consultations_id'), table_name='clinical_consultations')
    op.drop_table('clinical_consultations')
    op.drop_index(op.f('ix_clinical_files_id'), table_name='clinical_files')
    op.drop_table('clinical_files')
    # ### end Alembic commands ###
