"""add_medical_tags

Revision ID: 23993974fdbf
Revises: 59d4e54c6ba4
Create Date: 2026-06-03 11:42:17.678018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23993974fdbf'
down_revision: Union[str, Sequence[str], None] = '59d4e54c6ba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('color_hex', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_tags_id'), 'medical_tags', ['id'], unique=False)
    op.add_column('appointments', sa.Column('tag_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'medical_tags', ['tag_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'tag_id')
    op.drop_index(op.f('ix_medical_tags_id'), table_name='medical_tags')
    op.drop_table('medical_tags')
    # ### end Alembic commands ###
