"""add_commission_agreements

Revision ID: 59d4e54c6ba4
Revises: 8438801218ef
Create Date: 2026-06-03 11:11:23.087407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59d4e54c6ba4'
down_revision: Union[str, Sequence[str], None] = '8438801218ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('porcentaje_propuesto', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'ACEPTADO', 'RECHAZADO', name='commissionstate'), nullable=False),
    sa.Column('fecha_propuesta', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_respuesta', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commission_agreements_id'), 'commission_agreements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commission_agreements_id'), table_name='commission_agreements')
    op.drop_table('commission_agreements')
    # ### end Alembic commands ###
